# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build treez-be`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t treez-be`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system treez-be && \
          adduser --system -G treez-be treez-be

COPY dist/treez-be treez-be
RUN chown -R treez-be:treez-be .

CMD [ "node", "treez-be" ]
